name: 'split'
on:
  push:
    branches:
      - main
    tags:
      - '*'
jobs:
  packages_split:
    runs-on: ubuntu-latest
    environment: 'actions'
    env:
      GITHUB_TOKEN: ${{ secrets.SPLIT_ACCESS_TOKEN }}
    strategy:
      fail-fast: false
      matrix:
        packages:
          - local_path: 'slim-lti-gae-shim'
            split_repository: 'lti.slim-lti-gae-shim'
          - local_path: 'slim-lti-shim'
            split_repository: 'lti.slim-lti-shim'
        templates:
          - local_path: 'slim-lti-skeleton'
            split_repository: 'lti.slim-lti-skeleton'
    steps:
      - uses: actions/checkout@v2
      # no tag (packages)
      - if: "!startsWith(github.ref, 'refs/tags/')"
        uses: 'danharrin/monorepo-split-github-action@v2.3.0'
        with:
          package_directory: 'packages/${{ matrix.packages.local_path }}'
          repository_organization: 'groton-school'
          repository_name: '${{ matrix.packages.split_repository }}'
          user_name: 'battis'
          user_email: 'sbattis@groton.org'
      # with tag (packages)
      - if: "startsWith(github.ref, 'refs/tags/')"
        uses: 'danharrin/monorepo-split-github-action@v2.3.0'
        with:
          tag: ${GITHUB_REF#refs/tags/}
          package_directory: 'packages/${{ matrix.packages.local_path }}'
          repository_organization: 'groton-school'
          repository_name: '${{ matrix.packages.split_repository }}'
          user_name: 'battis'
          user_email: 'sbattis@groton.org'
      # no tag (templates)
      - if: "!startsWith(github.ref, 'refs/tags/')"
        uses: 'danharrin/monorepo-split-github-action@v2.3.0'
        with:
          package_directory: 'templates/${{ matrix.templates.local_path }}'
          repository_organization: 'groton-school'
          repository_name: '${{ matrix.templates.split_repository }}'
          user_name: 'battis'
          user_email: 'sbattis@groton.org'
      # with tag (templates)
      - if: "startsWith(github.ref, 'refs/tags/')"
        uses: 'danharrin/monorepo-split-github-action@v2.3.0'
        with:
          tag: ${GITHUB_REF#refs/tags/}
          package_directory: 'templates/${{ matrix.templates.local_path }}'
          repository_organization: 'groton-school'
          repository_name: '${{ matrix.templates.split_repository }}'
          user_name: 'battis'
          user_email: 'sbattis@groton.org'
